# render.yaml (в корне репо)

# 1) Persistent диск для uploaded-файлов
disks:
  - name: uploads-data
    size: 5Gi

# 2) PostgreSQL база
databases:
  - name: strapi-db
    databaseName: strapi
    user: strapi
    plan: free

# 3) Сервис Strapi
services:
  - type: web
    name: strapi
    # указываем папку с package.json Strapi
    root: backend
    # подключаем диск именно в папку public/uploads внутри backend
    disk: uploads-data
    diskMountPath: /opt/render/project/backend/public/uploads
    env: node
    plan: free

    # Сборка и запуск — переходим в backend перед командой
    buildCommand: |
      cd backend
      npm install
      npm run build
    startCommand: |
      cd backend
      npm start

    healthCheckPath: /_health

    envVars:
      - key: NODE_VERSION
        value: "18.17.0"
      - key: NODE_ENV
        value: production

      # Подключение Postgres
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: strapi-db
          property: connectionString

      # Переменные для Cloudinary
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
