disks:
  - name: uploads-data
    size: 5Gi

databases:
  - name: strapi-db
    databaseName: strapi
    user: strapi
    plan: free

services:
  - type: web
    name: strapi
    root: backend
    disk: uploads-data
    diskMountPath: /home/render/project/backend/public/uploads
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: strapi-db
          property: connectionString
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false