# render.yaml

# persistent диск для хранения uploaded-файлов
disks:
  - name: uploads-data
    size: 5Gi

# база данных PostgreSQL
databases:
  - name: strapi-db
    databaseName: strapi
    user: strapi
    plan: free

# сервис Strapi
services:
  - type: web
    name: strapi
    # корневая папка, в которой расположен package.json Strapi
    root: backend
    # используем созданный диск
    disk: uploads-data
    # монтируем его в папку public/uploads внутри src/backend
    diskMountPath: /opt/render/project/backend/public/uploads
    env: node
    plan: free
    # команды будут выполняться внутри src/backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: "18.17.0"
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: strapi-db
          property: connectionString
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: DATABASE_CLIENT
        value: postgres

  